import { readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..")
const sourcePath = resolve(root, "packages/tokens/src/tokens.json")
const outputPath = resolve(root, "packages/tokens/src/tokens.css")
const source = JSON.parse(readFileSync(sourcePath, "utf8"))

const variables = (prefix, values) =>
  Object.entries(values).map(
    ([name, value]) => `  --${prefix ? `${prefix}-` : ""}${name}: ${value};`,
  )

const css = [
  "/* Generated by scripts/tokens/generate.mjs from tokens.json. Do not edit. */",
  ":root,",
  '[data-theme="bivaque"] {',
  "  color-scheme: light;",
  "",
  "  /* Primitives: raw values; components use semantic roles. */",
  ...variables("primitive", source.primitive),
  "",
  "  /* Semantic tokens: stable product meaning. */",
  ...variables("semantic", source.semantic),
  "",
  "  /* Component tokens: wrappers bind contracts to semantic roles. */",
  ...variables("component", source.component),
  "",
  "  /* Permanent HeroUI theme adapter: library-facing names resolve to Bivaque tokens. */",
  ...variables("", source.web.aliases),
  "}",
  "",
].join("\n")

if (process.argv.includes("--check")) {
  if (readFileSync(outputPath, "utf8") !== css) {
    console.error("tokens.css is stale; run: node scripts/tokens/generate.mjs")
    process.exitCode = 1
  }
} else {
  writeFileSync(outputPath, css)
  console.log(`Generated ${outputPath}`)
}
