/// <reference types="expo/types" />

// NOTE: This file is auto-generated by `expo` CLI on first run. The stub here
// keeps `tsc --noEmit` green before the first `expo start` / `expo prebuild`,
// and is replaced once the CLI has a chance to write its real content.
